blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ è®¨è®ºå’Œå»ºè®®
    url: https://github.com/HK-bruc1/awesome-sites/discussions
    about: é¡¹ç›®ç›¸å…³çš„è®¨è®ºå’Œå»ºè®®
  - name: ğŸ“§ ç§äººåé¦ˆ
    url: mailto:fuxing319@gmail.com
    about: ç§å¯†çš„åé¦ˆå’Œå»ºè®®
